// resources/js/components/ATVListingCard.vue
<template>
  <div class="group hover:shadow-lg transition-all duration-300 overflow-hidden cursor-pointer bg-white border border-border rounded-lg">
    <div class="relative">
      <img
        v-if="listing?.active_images && listing.active_images.length > 0"
        :src="listing.active_images[0].url"
        :alt="listing.name"
        class="w-full h-48 object-cover group-hover:scale-105 transition-transform duration-300"
      />
      <button
        @click.stop="toggleFavorite"
        :class="[
          'absolute top-2 right-2 h-8 w-8 rounded-full flex items-center justify-center',
          isFavorited
            ? 'bg-red-500 text-white hover:bg-red-600'
            : 'bg-white/80 text-gray-600 hover:bg-white'
        ]"
      >
        <svg
          :class="['h-4 w-4', isFavorited ? 'fill-current' : '']"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
        </svg>
      </button>
      <span class="absolute top-2 left-2 px-2 py-1 bg-green-100 text-green-800 border border-green-200 rounded text-xs">
        {{ listing.year }}
      </span>
    </div>

    <div class="p-4">
      <div class="flex justify-between items-start mb-2">
        <h4 class="font-semibold text-md text-foreground group-hover:text-primary transition-colors">
          {{ listing.name }}
        </h4>
        <div class="text-right">
          <div class="text-xl font-bold text-primary">
            {{ formatPrice(Number(listing.price)) }}
          </div>
        </div>
      </div>

      <div class="grid grid-cols-2 gap-2 mb-3 text-sm text-muted-foreground">
        <div class="flex items-center gap-1">
          <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
          </svg>
          <span>{{ listing.year }} {{ t('listing.year') }}</span>
        </div>
        <div class="flex items-center gap-1 justify-end">
          <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z" />
          </svg>
          <span>{{ listing.mileage.toLocaleString() }} {{ t('listing.mileage') }}</span>
        </div>
        <div v-if="listing?.location" class="flex items-center gap-1">
          <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
          </svg>
          <span>{{ listing?.location?.name }}</span>
        </div>
        <div class="flex items-center gap-1 justify-end">
          <span class="font-medium">{{ listing.engine.replace('Engine', '') }}</span>
        </div>
      </div>

      <div class="flex flex-wrap gap-1 mb-3">
        <span class="px-2 py-1 bg-muted text-xs rounded">
          {{ listing.transmission }}
        </span>
      </div>

      <div class="flex items-center justify-between text-sm text-muted-foreground mb-3">
        <div class="flex items-center gap-2">
          <span class="text-blue-600 font-medium">
            {{ listing.fuel }}
          </span>
        </div>
        <span>{{ dateToLocale(listing.created_at) }}</span>
      </div>

      <div class="flex gap-2">
        <button class="flex-1 flex items-center justify-center gap-1 px-4 py-2 bg-atv-orange hover:bg-atv-orange-dark text-white rounded-md text-sm">
          <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
          </svg>
          {{ t('listing.call') }}
        </button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import { useLanguage } from '../composables/useLanguage';
import { dateToLocale } from '../lib/utils';

const props = defineProps({
  listing: {
    type: Object,
    required: true,
  },
});

const { t } = useLanguage();
const isFavorited = ref(false);

const formatPrice = (price) => {
  return `₾${price.toLocaleString()}`;
};

const toggleFavorite = () => {
  isFavorited.value = !isFavorited.value;
};
</script>

// markup/src/components/ATVListingCard.tsx
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Heart, MapPin, Calendar, Gauge, Phone, MessageSquare } from "lucide-react";
import { useState } from "react";
import { dateToLocale } from "@/lib/utils";
import { useLanguage } from "@/contexts/LanguageContext";

interface ATVListing {
  id: number;
  active_images: any[];
  name: string;
  price: string; // stored as string, not number
  year: number;
  clearance: string; // e.g. "8.5 inches"
  mileage: number;
  transmission: string;
  fuel: string;
  isActive: boolean;
  isVip: boolean;
  engine: string;
  description: string;
  created_at: string; // ISO timestamp
  updated_at: string; // ISO timestamp
  location_id: number | null;
  location?: {
    name: string;
  };
}

interface ATVListingCardProps {
  listing: ATVListing;
}

export const ATVListingCard = ({ listing }: ATVListingCardProps) => {
  const { t } = useLanguage();
  const [isFavorited, setIsFavorited] = useState(false);

  const formatPrice = (price: number) => {
    return `₾${price.toLocaleString()}`;
  };

  const getConditionColor = (condition: string) => {
    switch (condition.toLowerCase()) {
      case 'new':
      case 'ახალი':
        return 'bg-green-100 text-green-800 border-green-200';
      case 'excellent':
      case 'ძალიან კარგი':
        return 'bg-blue-100 text-blue-800 border-blue-200';
      case 'good':
      case 'კარგი':
        return 'bg-yellow-100 text-yellow-800 border-yellow-200';
      case 'fair':
      case 'საშუალო':
        return 'bg-orange-100 text-orange-800 border-orange-200';
      default:
        return 'bg-gray-100 text-gray-800 border-gray-200';
    }
  };

  return (
    <Card className="group hover:shadow-lg transition-all duration-300 overflow-hidden cursor-pointer">
      <div className="relative">
        {listing?.active_images.length > 0 && <img 
          src={listing?.active_images[0].url} 
          alt={listing.name}
          className="w-full h-48 object-cover group-hover:scale-105 transition-transform duration-300"
        />}
        <Button
          variant="ghost"
          size="icon"
          className={`absolute top-2 right-2 h-8 w-8 rounded-full ${isFavorited
            ? 'bg-red-500 text-white hover:bg-red-600'
            : 'bg-white/80 text-gray-600 hover:bg-white'
            }`}
          onClick={(e) => {
            e.stopPropagation();
            setIsFavorited(!isFavorited);
          }}
        >
          <Heart className={`h-4 w-4 ${isFavorited ? 'fill-current' : ''}`} />
        </Button>
        {/* {listing.originalPrice && listing.originalPrice > listing.price && (
          <Badge className="absolute bottom-2 left-2 bg-red-500 text-white">
            ფასდაკლება {Math.round(((listing.originalPrice - listing.price) / listing.originalPrice) * 100)}%
          </Badge>
        )} */}
        <Badge
          className={`absolute top-2 left-2 border bg-green-100 text-green-800 border-green-200`}
          variant="outline"
        >
          {listing.year}
        </Badge>
      </div>

      <div className="p-4">
        <div className="flex justify-between items-start mb-2">
          <h4 className="font-semibold text-md text-foreground group-hover:text-primary transition-colors">
            {listing.name}
          </h4>
          <div className="text-right">
            <div className="text-xl font-bold text-primary">
              {formatPrice(Number(listing.price))}
            </div>
            {/* {listing.originalPrice && listing.originalPrice > listing.price && (
              <div className="text-sm text-muted-foreground line-through">
                {formatPrice(listing.originalPrice)}
              </div>
            )} */}
          </div>
        </div>

        <div className="grid grid-cols-2 gap-2 mb-3 text-sm text-muted-foreground">
          <div className="flex items-center gap-1">
            <Calendar className="h-4 w-4" />
            <span>{listing.year} {t('listing.year')}</span>
          </div>
          <div className="flex items-center gap-1" style={{ justifyContent: 'end' }}>
            <Gauge className="h-4 w-4" />
            <span>{listing.mileage.toLocaleString()} {t('listing.mileage')}</span>
          </div>
          {listing?.location && <div className="flex items-center gap-1">
            <MapPin className="h-4 w-4" />
            <span>{listing?.location?.name}</span>
          </div>}
          <div className="flex items-center gap-1" style={{ justifyContent: 'end' }}>
            <span className="font-medium">{listing.engine.replace('Engine', '')}</span>
          </div>
        </div>

        <div className="flex flex-wrap gap-1 mb-3">
          <Badge variant="secondary" className="text-xs">
            {listing.transmission}
          </Badge>
          {/* {listing.features.slice(0, 3).map((feature, index) => (
            <Badge key={index} variant="secondary" className="text-xs">
              {feature}
            </Badge>
          ))}
          {listing.features.length > 3 && (
            <Badge variant="outline" className="text-xs">
              +{listing.features.length - 3} მეტი
            </Badge>
          )} */}
        </div>

        <div className="flex items-center justify-between text-sm text-muted-foreground mb-3">
          <div className="flex items-center gap-2">
            <span className="text-blue-600 font-medium">
              {listing.fuel}
            </span>
          </div>
          <span>{dateToLocale(listing.created_at)}</span>
        </div>

        <div className="flex gap-2">
          <Button size="sm" className="flex-1">
            <Phone className="h-4 w-4 mr-1" />
{t('listing.call')}
          </Button>
        </div>
      </div>
    </Card>
  );
};
