// markup/src/pages/Index.tsx
import { Header } from "@/components/Header";
import { HeroSection } from "@/components/HeroSection";
import { BrandLogos } from "@/components/BrandLogos";
import { FeaturedListings } from "@/components/FeaturedListings";
import { RecommendedATVs } from "@/components/RecommendedATVs";
import { ContentSections } from "@/components/ContentSections";
import { Footer } from "@/components/Footer";

const Index = () => {
  return (
    <div className="min-h-screen bg-background">
      <Header />
      <HeroSection />
      
      <FeaturedListings />
      <RecommendedATVs />
      <ContentSections />

      <BrandLogos />
      <Footer />
    </div>
  );
};

export default Index;

// resources/js/pages/Index.vue
<template>
  <Layout>
    <HeroSection />
    <FeaturedListings />
    <RecommendedATVs />
    <ContentSections />
    <BrandLogos />
  </Layout>
</template>

<script setup>
import Layout from '../components/Layout.vue';
import HeroSection from '../components/HeroSection.vue';
import FeaturedListings from '../components/FeaturedListings.vue';
import RecommendedATVs from '../components/RecommendedATVs.vue';
import ContentSections from '../components/ContentSections.vue';
import BrandLogos from '../components/BrandLogos.vue';
</script>
